Repository AY2021S2-CS2103T-T12-2/tp, pull requests merged in 2021-03, with the labels that each got.

#24 [Neo Soon Keat] Website: Update placeholder text and headers and include DG NFRs
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#25 [Song Soon Wee] Update README Ui.png
  docs/images/Ui.png
Labels: documentation

#29 Add weilianglol image
  docs/images/weilianglol.png
Labels: documentation

#30 [Kuah Wei Liang] Add BMI tracker to UserGuide.md
  docs/UserGuide.md
Labels: documentation

#37 [Song Soon Wee] Add validation check cases and test cases for Food
  src/main/java/seedu/address/model/food/Food.java
  src/test/java/seedu/address/model/food/FoodTest.java
Labels: type::feature

#45 Add User and Bmi model classes
  src/main/java/seedu/address/model/user/Bmi.java
  src/main/java/seedu/address/model/user/Name.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/model/user/BmiTest.java
  src/test/java/seedu/address/model/user/NameTest.java
  src/test/java/seedu/address/model/user/UserTest.java
Labels: type.Task

#51 User: Add Age field
  src/main/java/seedu/address/model/user/Age.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/model/user/AgeTest.java
Labels: priority.High, type.Task

#52 [Soh Jun Qi] Add progress calculator
  src/main/java/seedu/address/logic/FoodIntakeComparator.java
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/model/food/Food.java
Labels: type.Task

#53 [Song Soon Wee] Add Parser support for Food
  src/main/java/seedu/address/logic/commands/AddFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/ListFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/UpdateFoodItemCommand.java
  src/main/java/seedu/address/logic/parser/AddFoodItemCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteFoodItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateFoodItemCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/UniqueFoodList.java
  src/main/java/seedu/address/model/food/exceptions/DuplicateFoodItemException.java
  src/main/java/seedu/address/model/food/exceptions/FoodItemNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task

#55 [Kuah Wei Liang] Add unique food storage system
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/UpdateFoodItemCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/UniqueFoodList.java
  src/main/java/seedu/address/storage/JsonAdaptedFood.java
  src/main/java/seedu/address/storage/JsonSerializableUniqueFoodList.java
  src/main/java/seedu/address/storage/JsonUniqueFoodListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UniqueFoodListStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: severity.Medium, type.Task

#56 [Song Soon Wee] Update FoodIntakeList methods
  src/main/java/seedu/address/logic/FoodIntakeComparator.java
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/model/food/FoodIntakeList.java
  src/main/java/seedu/address/model/food/exceptions/FoodIntakeNotFoundException.java
Labels: priority.High, severity.High, type.Task

#60 [Soh Jun Qi] Change command format for certain commands
  docs/UserGuide.md
Labels: type.Documentation

#61 [Kuah Wei Liang] Patch model test
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Low

#65 [Soh Jun Qi] Add user initialization
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddUserCommand.java
  src/main/java/seedu/address/logic/parser/AddUserCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/user/Age.java
  src/main/java/seedu/address/model/user/Bmi.java
  src/main/java/seedu/address/model/user/Gender.java
  src/main/java/seedu/address/model/user/IdealWeight.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, type.Task

#68 [Song Soon Wee] Minor updates to Food parser
  src/main/java/seedu/address/logic/commands/AddFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFoodItemCommand.java
  src/main/java/seedu/address/logic/commands/UpdateFoodItemCommand.java
  src/main/java/seedu/address/logic/parser/AddFoodItemCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateFoodItemCommandParser.java
  src/main/java/seedu/address/model/food/Food.java
Labels: severity.High, type.Bug

#69 [Kuah Wei Liang] Add storage for diet plans
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/diet/DietPlanList.java
  src/main/java/seedu/address/storage/DietPlanListStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedDietPlan.java
  src/main/java/seedu/address/storage/JsonAdaptedFood.java
  src/main/java/seedu/address/storage/JsonDietPlanListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableDietPlanList.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#70 [Song Soon Wee] Fix bugs for FoodIntake Parser and messages
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/QueryFoodIntakeCommand.java
  src/main/java/seedu/address/logic/parser/AddFoodIntakeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteFoodIntakeCommandParser.java
  src/main/java/seedu/address/logic/parser/QueryFoodIntakeCommandParser.java
Labels: severity.High, type.Bug

#72 Update Progress Calculator to follow SLAP
  src/main/java/seedu/address/logic/ProgressCalculator.java
Labels: type.Task

#73 [Soh Jun Qi] Add diet plan functionalities
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ListDietPlansCommand.java
  src/main/java/seedu/address/logic/commands/RecommendPlanCommand.java
  src/main/java/seedu/address/logic/commands/SetActiveDietCommand.java
  src/main/java/seedu/address/logic/commands/ViewActiveDietCommand.java
  src/main/java/seedu/address/logic/commands/ViewPlanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetActiveDietCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewPlanCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/diet/DietPlan.java
  src/main/java/seedu/address/model/diet/DietPlanList.java
  src/main/java/seedu/address/model/diet/PlanType.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonAdaptedDietPlan.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/diet/DietPlanTest.java
Labels: type.Story, type.Task

#80 [Kuah Wei Liang] Add plan format
  src/main/java/seedu/address/model/diet/DietPlan.java
Labels: priority.Medium, type.Task

#81 [Song Soon Wee] Remove food intake list start date
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/AddUserCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/food/FoodIntakeList.java
  src/main/java/seedu/address/storage/JsonSerializableFoodIntakeList.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.High, priority.Medium, type.Bug

#82 [Song Soon Wee] Fix old food intake items from updating their values
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/FoodIntake.java
Labels: severity.High, type.Bug

#85 [Song Soon Wee] Update AddFoodIntake command
  src/main/java/seedu/address/logic/commands/AddFoodIntakeCommand.java
  src/main/java/seedu/address/logic/parser/AddFoodIntakeCommandParser.java
  src/main/java/seedu/address/model/food/Food.java
Labels: priority.Medium, type.Enhancement, type.Story

#89 [Soh Jun Qi] Implement progress calculator command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/PlanInfoCalculator.java
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/RunProgressCalculatorCommand.java
  src/main/java/seedu/address/logic/commands/ViewPlanCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story

#94 [Soh Jun Qi] Fix progress calculator issues
  src/main/java/seedu/address/logic/PlanInfoCalculator.java
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/RunProgressCalculatorCommand.java
Labels: priority.High, type.Bug, type.Task

#95 [Song Soon Wee] Update User Guide for Macronutrient Tracker
  docs/UserGuide.md
Labels: type.Documentation

#97 [Song Soon Wee] Update User Guide for MacroNutrient Tracker
  docs/UserGuide.md
Labels: type.Documentation

#99 [Neo Soon Keat] Update Gradle to evaluate assertions
  build.gradle
Labels: priority.Medium, type.Task

#102 [Soh Jun Qi] Update to progress report and fix bugs in adding food
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/parser/AddFoodItemCommandParser.java
Labels: priority.High, type.Bug, type.Task

#103 [Neo Soon Keat] Add User storage model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/user/Age.java
  src/main/java/seedu/address/model/user/Gender.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/JsonSerializableUser.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#106 [Kuah Wei Liang] Add diet plans to SampleDietUtil
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#107 [Song Soon Wee] Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#108 [Neo Soon Keat] Fix user storage bug with wrong file selection
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.High, type.Bug

#112 [Neo Soon Keat] Update DG with User implementation
  docs/DeveloperGuide.md
  docs/_config.yml
Labels: priority.Low, type.Documentation

#115 [Neo Soon Keat] Docs: Implement printing view fixes to title
  docs/_sass/minima/_base.scss
Labels: severity.VeryLow, type.Documentation

#116 [Soh Jun Qi] Update progress report format
  src/main/java/seedu/address/logic/ProgressCalculator.java
Labels: priority.Medium, type.Task

#120 [Soh Jun Qi] Removal of unused AB3 commands and parsing
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, type.Task

#122 [Song Soon Wee] Add sample template for first-time use
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/TemplateInitializer.java
Labels: priority.Medium, severity.Medium

#123 [Song Soon Wee] Update user guide
  docs/UserGuide.md
  docs/images/user-guide/add-food-intake-diff-food-item-result.png
  docs/images/user-guide/add-food-intake-new-food-item-result.png
  docs/images/user-guide/add-food-item-result.png
  docs/images/user-guide/delete-food-intake-result.png
  docs/images/user-guide/delete-food-item.png
  docs/images/user-guide/food-list-result.png
  docs/images/user-guide/query-food-intake-per-day.png
  docs/images/user-guide/query-food-intake-period.png
  docs/images/user-guide/start-up.png
  docs/images/user-guide/update-food-intake-item-result.png
  docs/images/user-guide/update-food-item-result.png
  src/main/java/seedu/address/logic/FoodIntakeQueryProcessor.java
  src/main/java/seedu/address/model/food/FoodIntake.java
Labels: type.Documentation

#128 [Neo Soon Keat] Storage: Add user storage to main functionality of program
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/user/Bmi.java
  src/main/java/seedu/address/model/user/IdealWeight.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Medium, type.Task

#129 [Soh Jun Qi] Update user guide
  docs/UserGuide.md
  docs/images/user-guide/bmi-query-result.png
  docs/images/user-guide/bmi-result.png
  docs/images/user-guide/plan-current-result.png
  docs/images/user-guide/plan-info-result.png
  docs/images/user-guide/plan-list-result.png
  docs/images/user-guide/plan-recommend-result.png
  docs/images/user-guide/plan-set-result.png
  docs/images/user-guide/progress-report.png
Labels: type.Documentation

#130 [Soh Jun Qi] Change parameters for calculateProgress method
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/RunProgressCalculatorCommand.java
Labels: type.Task

#131 [Jason Lim] Add intro and legend to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#132 [Song Soon Wee] Update User Guide
  docs/UserGuide.md
Labels: type.Documentation

#135 [Kuah Wei Liang] Add logo
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/dietlah-slim.png
  docs/images/dietlah.jpg
  docs/images/dietlah.png
Labels: severity.VeryLow, type.Documentation

#136 [Kuah Wei Liang] Update diet plan listings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/PlanInfoCalculator.java
  src/main/java/seedu/address/logic/commands/RecommendPlanCommand.java
  src/main/java/seedu/address/logic/commands/ViewPlanCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/diet/PlanType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/TemplateInitializer.java
Labels: priority.Medium, type.Documentation

#137 [Kuah Wei Liang] Adds back all missing titles
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/UserGuide.md
  docs/_layouts/page.html
  docs/index.md
Labels: priority.High, type.Documentation
