Repository AY2021S2-CS2103T-T12-2/tp, pull requests merged in 2021-04, with the labels that each got.

#138 [Kuah Wei Liang] Add content page info for UG
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#141 [Neo Soon Keat] Fix bugs with the food intake list not reflected in User object on creation
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/diet/DietPlan.java
  src/main/java/seedu/address/model/diet/MacroNutrientComposition.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/user/User.java
Labels: priority.High, type.Bug, type.Task

#139 [Song Soon Wee] Update DG UML diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#143 [Neo Soon Keat] Update User Guide with new information for 1.3
  docs/UserGuide.md
  docs/images/user-guide/dietlah-app.png
Labels: type.Documentation

#145 [Jason Lim] Fix reset command
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableFoodIntakeList.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserStorage.java
Labels: severity.Medium

#147 [Soh Jun Qi] Update plan details
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/ViewPlanCommand.java
  src/main/java/seedu/address/model/util/TemplateInitializer.java
Labels: type.Task

#149 [Soh Jun Qi] Revert changes to progress calculator
  src/main/java/seedu/address/logic/ProgressCalculator.java
  src/main/java/seedu/address/logic/commands/RunProgressCalculatorCommand.java
Labels: type.Bug

#150 [Soh Jun Qi] Update to user guide
  docs/UserGuide.md
  docs/images/user-guide/plan-info-result.png
  docs/images/user-guide/plan-list-result.png
  docs/images/user-guide/reset-blank.png
  docs/images/user-guide/reset-template.png
Labels: type.Documentation

#189 [Song Soon Wee] Branch fix food name restriction
  src/main/java/seedu/address/logic/parser/DeleteFoodIntakeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateFoodIntakeCommandParser.java
  src/main/java/seedu/address/model/food/Food.java
Labels: priority.High, type.Bug

#190 [Jason Lim] Address some PED concerns regarding Food Intakes and update User Guide
  docs/UserGuide.md
  docs/assets/css/style.scss
  src/main/java/seedu/address/logic/FoodIntakeQueryProcessor.java
  src/main/java/seedu/address/logic/commands/AddFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/UpdateFoodIntakeCommand.java
  src/main/java/seedu/address/logic/parser/DeleteFoodIntakeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateFoodIntakeCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/food/Food.java
  src/main/java/seedu/address/model/food/FoodIntakeList.java
  src/test/java/seedu/address/logic/commands/AddFoodItemCommandTest.java
Labels: severity.High, type.Bug, type.Documentation

#191 [Neo Soon Keat] Fix PE bugs
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/AddUserCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/QueryFoodIntakeCommand.java
  src/main/java/seedu/address/logic/commands/UpdateFoodIntakeCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.Medium

#192 [Jason Lim] Update Developer Guide, test cases and rename AddressBookParser
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddFoodIntakeActivityDiagram.png
  docs/images/AddFoodItemActivityDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteFoodIntakeActivityDiagram.png
  docs/images/DietPlanListClassDiagram.png
  docs/images/FoodClassDiagram.png
  docs/images/FoodIntakeClassDiagram.png
  docs/images/FoodIntakeListClassDiagram.png
  docs/images/FoodIntakeListFoodAssociationClassDiagram.png
  docs/images/UpdateFoodIntakeActivityDiagram.png
  docs/images/UserClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/DietLahParser.java
  src/test/java/seedu/address/logic/parser/DietLahParserTest.java
  src/test/java/seedu/address/model/food/FoodIntakeListTest.java
  src/test/java/seedu/address/model/food/FoodIntakeTest.java
Labels: priority.Medium, type.Documentation

#196 [Song Soon Wee] Fix Parser input and display messages
  src/main/java/seedu/address/logic/commands/AddFoodItemCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/food/Food.java
  src/test/java/seedu/address/logic/commands/AddFoodItemCommandTest.java
Labels: priority.High, type.Bug

#197 [Soh Jun Qi] Update PPP
  docs/team/sjq-sohjunqi.md
Labels: type.Documentation

#198 [Song Soon Wee] Update PPP
  docs/team/ssoonwee.md
Labels: type.Documentation

#200 [Song Soon Wee] Update Macronutrients UG
  docs/UserGuide.md
Labels: type.Documentation

#201 [Song Soon Wee] Fix Parser check for invalid days in February
  src/main/java/seedu/address/logic/parser/AddFoodIntakeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Bug

#203 [Jason Lim] Update GUI preview in User Guide
  docs/UserGuide.md
  docs/images/user-guide/gui.png
  docs/team/jasaaanlim.md
Labels: type.Documentation

#204 [Soh Jun Qi] Fix confusing identifiers for plan_recommend
  src/main/java/seedu/address/logic/commands/RecommendPlanCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddFoodItemCommandTest.java
Labels: type.Bug

#206 [Soh Jun Qi] Fix bug with processing of trailing zeros in bmi commands
  src/main/java/seedu/address/model/user/Bmi.java
  src/main/java/seedu/address/model/user/IdealWeight.java
Labels: type.Bug

#207 [Soh Jun Qi] Update exit command to be Diet Lah specific
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: severity.Low, type.Bug

#208 [Neo Soon Keat] Various documentation and screenshot updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/add-food-intake-diff-food-item-result.png
  docs/images/user-guide/add-food-intake-existing-food-item-result.png
  docs/images/user-guide/add-food-intake-new-food-item-result.png
  docs/images/user-guide/add-food-item-result.png
  docs/images/user-guide/bmi-query-result.png
  docs/images/user-guide/bmi-result.png
  docs/images/user-guide/delete-food-intake-result.png
  docs/images/user-guide/delete-food-item.png
  docs/images/user-guide/food-list-result.png
  docs/images/user-guide/plan-current-result.png
  docs/images/user-guide/plan-info-result.png
  docs/images/user-guide/plan-list-result.png
  docs/images/user-guide/plan-recommend-result.png
  docs/images/user-guide/plan-set-result.png
  docs/images/user-guide/progress-report.png
  docs/images/user-guide/query-food-intake-per-day.png
  docs/images/user-guide/query-food-intake-period.png
  docs/images/user-guide/reset-blank.png
  docs/images/user-guide/reset-template.png
  docs/images/user-guide/update-bmi-result.png
  docs/images/user-guide/update-food-intake-item-result.png
  docs/images/user-guide/update-food-item-result.png
Labels: priority.Medium, type.Documentation

#209 [Neo Soon Keat] Update UG screenshots after cropping
  docs/UserGuide.md
  docs/images/user-guide/plan-info-result.png
  docs/images/user-guide/plan-list-result.png
  docs/images/user-guide/update-food-intake-item-result.png
Labels: type.Documentation

#210 [Kuah Wei Liang] Add PPP for WeiLiang
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jasaaanlim.md
  docs/team/weilianglol.md
Labels: type.Documentation

#211 [Soh Jun Qi] Update PPP
  docs/team/sjq-sohjunqi.md
Labels: type.Documentation

#212 [Neo Soon Keat] Update DG with manual testing and effort sections
  docs/DeveloperGuide.md
  docs/team/soonkeatneo.md
Labels: type.Documentation

#214 [Soh Jun Qi] Remove duplicate entry in PPP
  docs/team/sjq-sohjunqi.md
Labels: type.Documentation

#215 [Neo Soon Keat] Fix DG formatting and update table of contents
  docs/DeveloperGuide.md
Labels: priority.Low, type.Documentation

#216 [Jason Lim] Update Developer Guide with AddFoodIntake Sequence Diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddFoodIntakeSequenceDiagram.puml
  docs/images/AddFoodIntakeSequenceDiagram.png
Labels: type.Documentation

#218 [Soh Jun Qi] Remove Persons from Diet Lah
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/DietLah.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyDietLah.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/DietLahStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonDietLahStorage.java
  src/main/java/seedu/address/storage/JsonSerializableDietLah.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonSerializableDietLahTest/duplicatePersonDietLah.json
  src/test/data/JsonSerializableDietLahTest/invalidPersonDietLah.json
  src/test/data/JsonSerializableDietLahTest/typicalPersonsDietLah.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddFoodItemCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/DietLahTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonDietLahStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableDietLahTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/DietLahBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalDietLah.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#219 [Song Soon Wee] Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteFoodItemActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListFoodItemActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/UniqueFoodListClassDiagram.puml
  docs/diagrams/UniqueFoodListFoodAssociationClassDiagram.puml
  docs/diagrams/UpdateFoodItemActivityDiagram.puml
  docs/images/DeleteFoodItemActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListFoodItemActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UniqueFoodListClassDiagram.png
  docs/images/UniqueFoodListFoodAssociationClassDiagram.png
  docs/images/UpdateFoodItemActivityDiagram.png
Labels: type.Documentation

#221 [Neo Soon Keat] DG: Update explanations and links from AB3
  docs/DeveloperGuide.md
Labels: type.Documentation

#222 [Neo Soon Keat] Various comments cleanup and fixes for generated JAR files
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/DietLah.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: priority.Medium

#223 [Song Soon Wee] Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddFoodItemSequenceDiagram.puml
  docs/diagrams/DeleteFoodItemSequenceDiagram.puml
  docs/images/AddFoodItemSequenceDiagram.png
  docs/images/DeleteFoodItemSequenceDiagram.png
Labels: type.Documentation

#226 [Song Soon Wee] Code cleanup
  src/main/java/seedu/address/model/food/FoodIntakeList.java
Labels: priority.High

#228 [Neo Soon Keat] Update PPP title formatting on page header
  docs/team/jasaaanlim.md
  docs/team/johndoe.md
  docs/team/sjq-sohjunqi.md
  docs/team/soonkeatneo.md
  docs/team/ssoonwee.md
  docs/team/weilianglol.md
Labels: type.Documentation

#229 [Jason Lim] Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DietPlanListClassDiagram.puml
  docs/diagrams/FoodClassDiagram.puml
  docs/diagrams/FoodIntakeClassDiagram.puml
  docs/diagrams/FoodIntakeListClassDiagram.puml
  docs/diagrams/FoodIntakeListFoodAssociationClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UniqueFoodListClassDiagram.puml
  docs/diagrams/UniqueFoodListFoodAssociationClassDiagram.puml
  docs/diagrams/UserClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#231 [Neo Soon Keat] Update Ui class diagram
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation

#235 [Kuah Wei Liang] Update DG Model
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/team/weilianglol.md
Labels: priority.High, type.Documentation

#234 [Soh Jun Qi] Fix bugs with various commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ProgressCalculatorClassDiagram.puml
  docs/images/ProgressCalculatorClassDiagram.png
  docs/team/jasaaanlim.md
  docs/team/sjq-sohjunqi.md
  docs/team/ssoonwee.md
  src/main/java/seedu/address/logic/commands/AddUserCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug

#236 [Jason Lim] Update Developer Guide class diagrams
  docs/diagrams/ProgressCalculatorClassDiagram.puml
  docs/images/DietPlanListClassDiagram.png
  docs/images/FoodClassDiagram.png
  docs/images/FoodIntakeClassDiagram.png
  docs/images/FoodIntakeListClassDiagram.png
  docs/images/FoodIntakeListFoodAssociationClassDiagram.png
  docs/images/ProgressCalculatorClassDiagram.png
  docs/images/UniqueFoodListClassDiagram.png
  docs/images/UniqueFoodListFoodAssociationClassDiagram.png
  docs/images/UserClassDiagram.png
Labels: type.Documentation

#237 [Jason Lim] Update bmi_query screenshot
  docs/images/user-guide/bmi-query-result.png
Labels: type.Documentation

#239 [Soh Jun Qi] Update sequence diagram for ProgressCalculator
  docs/DeveloperGuide.md
  docs/diagrams/ProgressCalculatorSequenceDiagram.puml
  docs/images/ProgressCalculatorSequenceDiagram.png
  docs/team/sjq-sohjunqi.md
Labels: type.Documentation

#240 Update screenshot in UG for recommend diet plan
  docs/images/user-guide/plan-recommend-result.png
Labels: type.Documentation

#241 [Jason Lim] Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#244 [Song Soon Wee] Fix DG bugs
  docs/DeveloperGuide.md
  docs/diagrams/AddFoodItemSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/AddFoodItemSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation

#245 [Neo Soon Keat] Update line break locations
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#246 [Neo Soon Keat] Remove placeholder lines from DG and update effort section
  docs/DeveloperGuide.md
Labels: type.Documentation
